#!/usr/bin/env bash
# Traefik first-boot configure:
#   1. Render acme.env from the DNS provider credentials
#   2. Create OIDC clients in Keycloak for traefik-forward-auth and filebrowser
#   3. Generate the Traefik dynamic config from all services' proxy: blocks
#   4. Start Traefik (+ forward-auth + filebrowser) via systemd
#
# OIDC clients for other services are created by THEIR own configure.sh,
# via the shared helper /opt/personal-server/lib/keycloak.sh.

set -euo pipefail

TRAEFIK_DIR=/var/lib/personal-server/traefik
CONF_DIR=/etc/personal-server
SERVICES_DIR=$CONF_DIR/services
DOMAIN=${PS_DOMAIN:?}
KC_LOCAL=http://localhost:8180
REALM=personal-server

# Make sure the runtime tree exists. install.sh stages templates into
# /opt/personal-server/traefik/, but the runtime dirs in /var/lib/… are
# our responsibility — including the dynamic/ subtree where we write
# the Traefik file-provider config a few steps below.
install -d -m 0755 "$TRAEFIK_DIR" "$TRAEFIK_DIR/dynamic" "$TRAEFIK_DIR/letsencrypt"

# ── 1. acme.env from the credentials file ───────────────────────────
ACME_ENV=$TRAEFIK_DIR/acme.env
: > "$ACME_ENV"
chmod 600 "$ACME_ENV"
CREDS_FILE=$CONF_DIR/acme-credentials.yaml
if [[ -f $CREDS_FILE ]] && [[ $(yq 'length' "$CREDS_FILE") -gt 0 ]]; then
  yq -r 'to_entries[] | "\(.key)=\(.value)"' "$CREDS_FILE" >> "$ACME_ENV"
fi

# ── 2. Create OIDC clients in Keycloak (best-effort) ────────────────
# OIDC client creation can fail on a slow CI/first-boot (Keycloak's
# master realm init is not instantaneous after the health endpoint
# returns). The proxy itself doesn't need OIDC to start — the operator
# can re-run this setup later with `personal-server reconfigure`.
# Never let an OIDC blip prevent systemctl enable below.
source /opt/personal-server/keycloak/lib/keycloak.sh
if KC_TOKEN=$(keycloak_admin_token); then
  # forward-auth uses a SINGLE central /_oauth callback at AUTH_HOST
  # (auth.${DOMAIN}/_oauth), regardless of which protected subdomain
  # initiated the login. Register that exact URI — Keycloak's wildcard
  # matching on subdomains in the host part is flaky depending on
  # version and refused with 'Invalid parameter: redirect_uri' here.
  keycloak_ensure_client "$KC_TOKEN" "$REALM" "traefik-forward-auth" \
    "${PS_TRAEFIK_FORWARD_AUTH_CLIENT_SECRET}" \
    "https://auth.${DOMAIN}/_oauth" \
    || echo "traefik: warn — forward-auth OIDC client create failed (keycloak transient), will retry on next reconfigure" >&2
  keycloak_ensure_client "$KC_TOKEN" "$REALM" "filebrowser" \
    "${PS_FILEBROWSER_CLIENT_SECRET}" \
    "https://files.${DOMAIN}/api/auth/oidc/callback" \
    || echo "traefik: warn — filebrowser OIDC client create failed (keycloak transient), will retry on next reconfigure" >&2
else
  echo "traefik: warn — keycloak admin token unavailable, skipping OIDC client creation (re-run with personal-server reconfigure)" >&2
fi

# ── 3. Generate dynamic config from every service's proxy: block ────
DYNAMIC=$TRAEFIK_DIR/dynamic/services.yml
{
  echo "# Auto-generated by traefik configure.sh from services/*/service.yaml"
  echo "http:"
  echo "  middlewares:"
  echo "    forward-auth:"
  echo "      forwardAuth:"
  echo "        address: \"http://forward-auth:4181\""
  echo "        trustForwardHeader: true"
  echo "        authResponseHeaders:"
  echo "          - X-Forwarded-User"
  echo "  routers:"
  # forward-auth's auth-host mode: the OIDC callback comes back to
  # https://auth.<domain>/_oauth — but auth.<domain> is otherwise routed
  # to Keycloak, which doesn't know /_oauth and returns 'Page not found'.
  # Add a higher-priority router that catches /_oauth on the auth host
  # and sends it to the forward-auth container; everything else on
  # auth.<domain> still falls through to Keycloak's regular router.
  echo "    forward-auth-callback:"
  echo "      rule: \"Host(\`auth.${DOMAIN}\`) && PathPrefix(\`/_oauth\`)\""
  echo "      service: forward-auth"
  echo "      priority: 100"
  echo "      entryPoints: [websecure]"
  echo "      tls:"
  echo "        certResolver: letsencrypt"
  for yaml in "$SERVICES_DIR"/*/service.yaml; do
    [[ -f $yaml ]] || continue
    t=$(yq -r '.proxy // "" | type' "$yaml")
    [[ $t == "!!map" ]] || continue
    name=$(yq -r '.name' "$yaml")
    sub=$(yq -r '.proxy.subdomain // .name' "$yaml")
    auth=$(yq -r '.proxy.auth // "sso"' "$yaml")
    echo "    $name:"
    echo "      rule: \"Host(\`${sub}.${DOMAIN}\`)\""
    echo "      service: $name"
    echo "      entryPoints: [websecure]"
    echo "      tls:"
    echo "        certResolver: letsencrypt"
    case $auth in
      public)
        ;;
      forward-auth|sso)
        echo "      middlewares: [forward-auth]"
        ;;
    esac
  done
  echo "  services:"
  echo "    forward-auth:"
  echo "      loadBalancer:"
  echo "        servers:"
  echo "          - url: \"http://forward-auth:4181\""
  for yaml in "$SERVICES_DIR"/*/service.yaml; do
    [[ -f $yaml ]] || continue
    t=$(yq -r '.proxy // "" | type' "$yaml")
    [[ $t == "!!map" ]] || continue
    name=$(yq -r '.name' "$yaml")
    upstream=$(yq -r '.proxy.upstream' "$yaml")
    echo "    $name:"
    echo "      loadBalancer:"
    echo "        servers:"
    echo "          - url: \"$upstream\""
  done
} > "$DYNAMIC"
chmod 644 "$DYNAMIC"

# ── 4. Start Traefik ────────────────────────────────────────────────
docker network create coolify 2>/dev/null || true
systemctl daemon-reload
systemctl enable --now personal-server-traefik.service

echo "traefik: ready. dashboard at http://localhost:8080 (local only)"
