#!/usr/bin/env bash
# Traefik first-boot configure:
#   1. Render acme.env from the DNS provider credentials
#   2. Create OIDC clients in Keycloak for traefik-forward-auth and filebrowser
#   3. Generate the Traefik dynamic config from all services' proxy: blocks
#   4. Start Traefik (+ forward-auth + filebrowser) via systemd
#
# OIDC clients for other services are created by THEIR own configure.sh,
# via the shared helper /opt/personal-server/lib/keycloak.sh.

set -euo pipefail

TRAEFIK_DIR=/var/lib/personal-server/traefik
CONF_DIR=/etc/personal-server
SERVICES_DIR=$CONF_DIR/services
DOMAIN=${PS_DOMAIN:?}
KC_LOCAL=http://localhost:8180
REALM=personal-server

# ── 1. acme.env from the credentials file ───────────────────────────
ACME_ENV=$TRAEFIK_DIR/acme.env
: > "$ACME_ENV"
chmod 600 "$ACME_ENV"
CREDS_FILE=$CONF_DIR/acme-credentials.yaml
if [[ -f $CREDS_FILE ]] && [[ $(yq 'length' "$CREDS_FILE") -gt 0 ]]; then
  yq -r 'to_entries[] | "\(.key)=\(.value)"' "$CREDS_FILE" >> "$ACME_ENV"
fi

# ── 2. Get a Keycloak admin token ───────────────────────────────────
source /opt/personal-server/keycloak/lib/keycloak.sh
KC_TOKEN=$(keycloak_admin_token)

# Create OIDC client for traefik-forward-auth (confidential, with redirect URI)
keycloak_ensure_client "$KC_TOKEN" "$REALM" "traefik-forward-auth" \
  "${PS_TRAEFIK_FORWARD_AUTH_CLIENT_SECRET}" \
  "https://*.${DOMAIN}/_oauth"

# Create OIDC client for filebrowser (if filebrowser supports OIDC)
keycloak_ensure_client "$KC_TOKEN" "$REALM" "filebrowser" \
  "${PS_FILEBROWSER_CLIENT_SECRET}" \
  "https://files.${DOMAIN}/api/auth/oidc/callback"

# ── 3. Generate dynamic config from every service's proxy: block ────
DYNAMIC=$TRAEFIK_DIR/dynamic/services.yml
{
  echo "# Auto-generated by traefik configure.sh from services/*/service.yaml"
  echo "http:"
  echo "  middlewares:"
  echo "    forward-auth:"
  echo "      forwardAuth:"
  echo "        address: \"http://forward-auth:4181\""
  echo "        trustForwardHeader: true"
  echo "        authResponseHeaders:"
  echo "          - X-Forwarded-User"
  echo "  routers:"
  for yaml in "$SERVICES_DIR"/*/service.yaml; do
    [[ -f $yaml ]] || continue
    t=$(yq -r '.proxy // "" | type' "$yaml")
    [[ $t == "!!map" ]] || continue
    name=$(yq -r '.name' "$yaml")
    sub=$(yq -r '.proxy.subdomain // .name' "$yaml")
    auth=$(yq -r '.proxy.auth // "sso"' "$yaml")
    echo "    $name:"
    echo "      rule: \"Host(\`${sub}.${DOMAIN}\`)\""
    echo "      service: $name"
    echo "      entryPoints: [websecure]"
    echo "      tls:"
    echo "        certResolver: letsencrypt"
    case $auth in
      public)
        ;;
      forward-auth|sso)
        echo "      middlewares: [forward-auth]"
        ;;
    esac
  done
  echo "  services:"
  for yaml in "$SERVICES_DIR"/*/service.yaml; do
    [[ -f $yaml ]] || continue
    t=$(yq -r '.proxy // "" | type' "$yaml")
    [[ $t == "!!map" ]] || continue
    name=$(yq -r '.name' "$yaml")
    upstream=$(yq -r '.proxy.upstream' "$yaml")
    echo "    $name:"
    echo "      loadBalancer:"
    echo "        servers:"
    echo "          - url: \"$upstream\""
  done
} > "$DYNAMIC"
chmod 644 "$DYNAMIC"

# ── 4. Start Traefik ────────────────────────────────────────────────
docker network create coolify 2>/dev/null || true
systemctl daemon-reload
systemctl enable --now personal-server-traefik.service

echo "traefik: ready. dashboard at http://localhost:8080 (local only)"
