#!/usr/bin/env bash
# Arcane configure.sh — called by the wizard.
# Secrets come from service.yaml's secrets: block, auto-generated by
# render-all-units.sh and available as PS_ARCANE_* in env.
set -euo pipefail

DOMAIN=${PS_DOMAIN:?PS_DOMAIN must be set by the wizard}
ENCRYPTION_KEY=${PS_ARCANE_ENCRYPTION_KEY:?must be set by render-all-units}
JWT_SECRET=${PS_ARCANE_JWT_SECRET:?must be set by render-all-units}
ENV_FILE=/etc/personal-server/arcane.env

if [[ ! -f $ENV_FILE ]]; then
  install -d -m 0755 /etc/personal-server
  umask 077
  cat > "$ENV_FILE" <<EOF
APP_URL=https://docker.${DOMAIN}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
JWT_SECRET=${JWT_SECRET}
PUID=0
PGID=0
EOF
fi

install -d -m 0755 /var/lib/personal-server/arcane
# Network `coolify` is created by pangolin's compose (depends_on: pangolin).
systemctl enable --now personal-server-arcane.service
